### ISSUE TITLE
new version generates builderror

### ISSUE THREAD

**Issue by roscoedeemarutam** [RSuter/NSwag#1576] opened 2018-09-05 12:09 UTC
hi,

I just installed the new version of nswagstudio and without doing anything i get this error.

tonsoft.Json.JsonSerializationException: Error setting value to 'SelectedSwaggerGeneratorRaw' on 'NSwag.Commands.NSwagDocument'. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Hosting.Abstractions, Version=1.0.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.
Check if .NET Core is installed and 'dotnet' is globally available.

I'm not using .net core.
please advise.

my nswag file:

{
  "runtime": "Default",
  "defaultVariables": null,
  "swaggerGenerator": {
    "webApiToSwagger": {
      "controllerNames": [
        "Euromex.Web.Controller.Webconsultatie.DocumentWebConsultatieController",
        "Euromex.Web.Controller.Webconsultatie.DossierWebConsultatieController",
        "Euromex.Web.Controller.Webconsultatie.MakelaarWebConsultatieController"
      ],
      "isAspNetCore": false,
      "defaultUrlTemplate": "api/{controller}/{id?}",
      "addMissingPathParameters": false,
      "defaultPropertyNameHandling": "CamelCase",
      "defaultReferenceTypeNullHandling": "Null",
      "defaultEnumHandling": "Integer",
      "flattenInheritanceHierarchy": false,
      "generateKnownTypes": false,
      "generateXmlObjects": false,
      "generateAbstractProperties": false,
      "ignoreObsoleteProperties": false,
      "allowReferencesWithProperties": true,
      "excludedTypeNames": [],
      "serviceHost": null,
      "serviceBasePath": null,
      "serviceSchemes": [],
      "infoTitle": "DocumentWebConsultatieController",
      "infoDescription": "The Document controller for the Web consultation app",
      "infoVersion": "1.0.0",
      "includedVersions": null,
      "documentTemplate": null,
      "documentProcessorTypes": [],
      "operationProcessorTypes": [],
      "typeNameGeneratorType": null,
      "schemaNameGeneratorType": null,
      "contractResolverType": null,
      "serializerSettingsType": null,
      "output": "../Content/Swagger specs/DocumentWebConsultatieControllerSpec.json",
      "outputType": "Swagger2",
      "assemblyPaths": [
        "../bin/Euromex.Web.dll"
      ],
      "assemblyConfig": "../Web.config",
      "referencePaths": []
    }
  },
  "codeGenerators": {
    "swaggerToTypeScriptClient": {
      "className": "{controller}Service",
      "moduleName": "",
      "namespace": "",
      "typeScriptVersion": 2.7,
      "template": "Angular",
      "promiseType": "Promise",
      "httpClass": "HttpClient",
      "useSingletonProvider": true,
      "injectionTokenType": "InjectionToken",
      "rxJsVersion": 6.0,
      "dateTimeType": "String",
      "nullValue": "Undefined",
      "generateClientClasses": true,
      "generateClientInterfaces": false,
      "generateOptionalParameters": true,
      "exportTypes": true,
      "wrapDtoExceptions": false,
      "clientBaseClass": "",
      "wrapResponses": false,
      "wrapResponseMethods": [],
      "generateResponseClasses": true,
      "responseClass": "SwaggerResponse",
      "protectedMethods": [],
      "configurationClass": "",
      "useTransformOptionsMethod": false,
      "useTransformResultMethod": false,
      "generateDtoTypes": true,
      "operationGenerationMode": "MultipleClientsFromOperationId",
      "markOptionalProperties": true,
      "generateCloneMethod": false,
      "typeStyle": "Class",
      "classTypes": [],
      "extendedClasses": [],
      "extensionCode": null,
      "generateDefaultValues": true,
      "excludedTypeNames": [],
      "handleReferences": false,
      "generateConstructorInterface": true,
      "convertConstructorInterfaceData": false,
      "importRequiredTypes": true,
      "useGetBaseUrlMethod": false,
      "baseUrlTokenName": "API_BASE_URL",
      "queryNullValue": "",
      "templateDirectory": null,
      "typeNameGeneratorType": null,
      "propertyNameGeneratorType": null,
      "enumNameGeneratorType": null,
      "serviceHost": null,
      "serviceSchemes": null,
      "output": "../../Euromex.WebConsultatie/src/app/services/Generated/WebConsultatie.WebApi.Generated.Service.ts"
    }
  }
}

**Comment by roscoedeemarutam** [comment] 2018-09-05 12:29
is there a way to downgrade and install the version I had again?

**Comment by RSuter** [comment] 2018-09-05 12:31
Sure, just reinstall v11.18.7... but i'd really like to fix this assembly loading problem. However I am getting crazy with all these assembly loading problems all the time...

**Comment by roscoedeemarutam** [comment] 2018-09-05 12:39
I understand... but at the moment I'm not able to spend much time looking. :( 
I'm on a very tight deadline, so I just need a working version momentarily.

**Comment by Zaismussen** [comment] 2018-09-05 16:01
I'm having the same problem with every regular .Net Framework project I try to generate from.  I'm attaching an example that manifests the error for me.  The nswag file I used in NSwagStudio is in the root of the project folder.

[SwaggerErrorTest.zip](https://github.com/RSuter/NSwag/files/2353563/SwaggerErrorTest.zip)

**Comment by RSuter** [comment] 2018-09-05 16:11
Ok thanks will look into this soon, just stay on the old version until we have a fix

**Comment by Zaismussen** [comment] 2018-09-05 16:21
I don't seem to have a copy of the old version, and haven't been able to find a link to it.  Where can I get it?

**Comment by mark-richardson-finsuite** [comment] 2018-09-06 01:16
@Zaismussen, if you use chocolatey:

    choco install nswagstudio --version 11.18.7

Chocolately can be downloaded by following these instructions: https://chocolatey.org/install

**Comment by RSuter** [comment] 2018-09-06 07:55
Hmm, it works for me, even without the NuGet cache option: 

![image](https://user-images.githubusercontent.com/2603405/45143235-f8bd7780-b1ba-11e8-96c6-8980460f4ab8.png)

**Comment by Zaismussen** [comment] 2018-09-06 13:12
Let me know if there's anything I can do to help figure it out.  I will probably have some time today and tomorrow to mess around with it, and I can probably survive a few days before downgrading if necessary.

**Comment by RSuter** [comment] 2018-09-06 13:34
We really need a sample where we can repro this and which i can add to the test suite to avoid regressions in the future

**Comment by RSuter** [comment] 2018-09-06 13:37
> Adding the local nuget cache folder doesn't work!! as far as i understand its missing 'Microsoft.AspNetCore.Hosting.Abstractions' and I'm not using .net core??

The generator has a dependency on core but it should work without that...

**Comment by xinyuewu** [comment] 2018-09-14 09:51
Hi guys, I'm having exactly the same issue. Where can I get a microsoft installer for version 11.18.* or below? All installers I've found so far are the latest (11.19.0)

**Comment by RSuter** [comment] 2018-09-14 09:52
In the github releases page you can find all old installers

**Comment by xinyuewu** [comment] 2018-09-14 09:59
> In the github releases page you can find all old installers

Got it! Thank you very much!

**Comment by zengouu** [comment] 2018-10-04 07:02
Just updated to 11.20.1.0 and this issue still persists. Regular (non-Core) .NET Framework Web Api project.

**Comment by MaximBalaganskiy** [comment] 2018-10-24 03:54
I observe the same upgrading from 11.17.19 to 11.20.1.
I noticed that the latest version uses `Microsoft.AspNetCore.Hosting.Abstractions.dll` 1.0.5.31018 of 26/10/85 as opposed to the older version which uses `Microsoft.AspNetCore.Hosting.Abstractions.dll` 1.1.3.30908 of 09/09/17. I am pretty sure this is what's causing the exception.

**Comment by RSuter** [comment] 2018-10-24 06:13
Did you try using a newer runtime, eg NetCore21?

**Comment by MaximBalaganskiy** [comment] 2018-10-24 06:17
My project has to be full .net x86, unfortunately

**Comment by RSuter** [comment] 2018-10-24 13:28
I think we should change the dependency of the full .NET package to ASP.NET Core 2.0 then... the older libraries are no longer supported anyway...

**Comment by MaximBalaganskiy** [comment] 2018-10-25 22:44
Why not change the dependency to what it used to be in older versions? Those worked just fine.

**Comment by roscoedeemarutam** [comment] 2018-10-30 15:16
just for the record. I had to change computer and with reinstalling everything. the latest version of nswagstudio is working perfectly!

**Comment by MirKml** [comment] 2018-11-01 12:07
If I need to generate typescript from full .net 4.7 assembly, issue is still presented. I have also installed .net core 21. Change the runtime to NetCore21 doesn't help.

**Comment by RSuter** [comment] 2018-11-01 12:15
@MirKml is the problem the spec generation or typescript generation?

**Comment by MirKml** [comment] 2018-11-01 14:32
@RSuter Hm, this is little bit weird. When I upgraded from 11.18.7 via built in upgrading process to 11.20.1 then after newly upgraded nswag studio is started, I want to generate Typescript from .net 4.7 assembly, nswag crashes with the

```
Newtonsoft.Json.JsonSerializationException: Error setting value to 'SelectedSwaggerGeneratorRaw' on 'NSwag.Commands.NSwagDocument'. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Hosting.Abstractions, Version=1.0.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.
Check if .NET Core is installed and 'dotnet' is globally available.
Runtime: Default
```
After change runtime to NetCore21 and trying to do same thing, error is

```
TypeLoadException: Could not load type 'System.Web.UI.Page' from assembly 'System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
Try running the document in another runtime, e.g. /runtime:NetCore20
Runtime: NetCore21
```
It makes sense, I cannot load .net 4.7 assembly when netcore21 runtime is used.

But when I download latest zip package from the http://rsuter.com/Projects/NSwagStudio/archive.php. Everything works fine. Maybe also with the uninstall and install via msi, but I don't tested. So maybe bug is somewhere in the MSI, upgrade process or something like that.

**Comment by MirKml** [comment] 2018-11-01 14:39
Uninstall and install new version also works. So problem is definitely somewhere in upgrading process from 11.18.7 to newer version. But unistall and install is reasonable workaround. So I think it can be closed.

**Comment by MaximBalaganskiy** [comment] 2018-11-01 20:02
It's not just about the studio. Npm packages are also affected

**Comment by RSuter** [comment] 2018-11-01 21:10
Yes? This is really strange as all binaries should be replaced, etc.

**Comment by RSuter** [comment] 2018-11-01 21:11
You’renot using one of the ci build artifacts with the same version as the current released one?

**Comment by MaximBalaganskiy** [comment] 2018-11-01 21:13
All I'm doing is npm I nswag... Latest version brings those weird old DLLs,
previous version has proper ones

**Comment by RSuter** [comment] 2018-11-01 21:16
But the version in the generated artifacts is correct?

**Comment by MaximBalaganskiy** [comment] 2018-11-01 21:21
I don't use nswag nuget package in the asp.net project itself, just the npm
package. Same artifacts work fine with older nswag cli. The problem is in
the content of the latest npm package

**Comment by RSuter** [comment] 2018-11-01 21:31
Yes, but the version in the generated spec or code is correct?

**Comment by MaximBalaganskiy** [comment] 2018-11-01 21:34
Latest cli fails, so no typescript code gets generated yet. Besides the cli
output the project does not have any nswag dependencies

**Comment by RSuter** [comment] 2018-11-01 21:56
It seems that I had problems publishing to NPM in the v11.20.1 release so I had to manually release it - I think that an old version or something must have slipped in there... will investigate. A new version will be released in the next days anyway...

**Comment by juveilko** [comment] 2018-11-02 13:10
When running latest version 11.20.1.0 from command line in windows environment, it crashed because of missing dlls. I worked around this issue by copying the missing dll from the "NSwagStudio" folder into the Win sub-folder as I kept encountering them. Eventually, I managed to run Nswag successfully.

If I recall correctly the dlls I copied were Microsoft.AspNetCore.:
* Hosting.Abstractions
* Hosting.Server.Abstractions
* Http.Features
* TestHost

I am not 100% sure those were all.

**Closed** 2018-11-05 17:33 UTC
Labels: priority: high, state: await-repro, type: bug

**Comment by jepperaskdk** [comment] 2023-12-25 21:32
@RicoSuter I'm getting this error after trying to upgrade to .NET 8.0, using version `14.0.0-preview012`. In nswag.json I set `"runtime": "Net80"`.

From this command:
dotnet "C:\Users\USER\.nuget\packages\nswag.msbuild\14.0.0-preview012\buildTransitive\../tools/Net80/dotnet-nswag.dll" run nswag.json

```
Newtonsoft.Json.JsonSerializationException: Error setting value to 'SelectedSwaggerGeneratorRaw' on 'NSwag.Commands.NSwagDocument'.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at NSwag.Commands.NSwagDocumentBase.set_SelectedSwaggerGeneratorRaw(JObject value) in /_/src/NSwag.Commands/NSwagDocumentBase.cs:line 88
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.SetValue(Object target, Object value)
   --- End of inner exception stack trace ---
```
