### ISSUE TITLE
Link support. Open API v3

### ISSUE THREAD

**Issue by Havunen** [RSuter/NSwag#1720] opened 2018-11-06 19:48 UTC
Hi

Does NSwag support open API 3 link objects? If so: where is the documentation?

Im not interested in client generation, but server side documentation generation. Im trying to make our API consumable by robots and this feature would help a lot. 

https://swagger.io/docs/specification/links/

I need to able to define relation between multiple objects so the robots understand it. If this is supported how would it work? Data attributes at model level or how? Im looking for solution for our .net API and cant find anything :/

**Comment by RSuter** [comment] 2018-11-06 20:00
No this is not supported yet. How would you envision the api for that?

**Comment by RSuter** [comment] 2018-11-07 08:14
Duplicate of: https://github.com/RSuter/NSwag/issues/1405

**Closed** 2018-11-07 08:35 UTC
Labels: duplicate, format: OpenAPI 3, project: NSwag.SwaggerGeneration.AspNetCore
