### ISSUE TITLE
"Consumes" attribute on controller action ignored 

### ISSUE THREAD

**Issue by georgeonofrei** [RSuter/NSwag#420] opened 2016-11-16 08:45 UTC
"Consumes" attribute on controller action does not generate the swagger.json with a "path" with the indicated "consumes" property

**Comment by rsuter** [comment] 2016-11-16 17:29
Can you provide a sample action method and the expected swagger json?

**Comment by rsuter** [comment] 2016-11-17 08:17
https://docs.microsoft.com/en-us/aspnet/core/api/microsoft.aspnetcore.mvc.consumesattribute

**Comment by georgeonofrei** [comment] 2016-12-03 15:10
I expect the consume attribute to generate the right section in open api. Usually the consumes per action means an overwrite of the configured per website consumes.
I have a situation in which the web api usually consumes Json, but some actions consume form/encoded.

**Comment by TheSilvermind** [comment] 2018-12-21 11:37
I noticed this is still an open issue. Is there any progress on this? Or can I do this any another way?

**Comment by RSuter** [comment] 2018-12-21 11:46
Can you provide a sample operation to reproduce this?

**Comment by RSuter** [comment] 2018-12-21 12:51
I've created a PR: Can you check the test and the rest? Is this what you'd expect?

https://github.com/RSuter/NSwag/pull/1849

**Comment by TheSilvermind** [comment] 2018-12-21 19:30
Yes, this works. The `Try it out` functionallity is working now with the proper Content-Type. Sorry I could not reply to you sooner, but thanks very much for taking your time. Very much appreciated.

**Comment by LockTar** [comment] 2019-02-21 06:58
@RSuter any idea when this will be implemented? Is it correct that we can use the `Consumes` attribute on Action methods for ASP .NET Core?

**Comment by RSuter** [comment] 2019-02-22 06:59
@LockTar will check ASAP. There must have been some problems otherwise i would have merged it :-)

**Comment by LockTar** [comment] 2019-02-27 07:39
Hi @RSuter, did you found an issue?

**Comment by RSuter** [comment] 2019-02-27 16:39
See @pranavkm answer in the PR: 

> `ConsumesAttribute` works in tandem with formatters - the idea is that you can only consume a media type that you could read from the body. It's likely that there isn't a formatter for `text/html` in your test above. Here's the relevant piece of code: https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.ApiExplorer/DefaultApiDescriptionProvider.cs#L426-L461

**Comment by LockTar** [comment] 2019-02-28 08:36
Hi @RSuter, sorry I don't understand your reply. I checked the PR but I think I do the same as in the PR.
I have a Controller with the attributes:

```c#
[Produces("application/json")]
[ApiController]
```

I than have an action with the following attributes:

```c#
[HttpPost("add")]
[Consumes("application/json")]
[ProducesResponseType(201)]
[ProducesResponseType(400)]
```

In the swagger.json, in the "add" path i have:

```json
"consumes": [
"application/json-patch+json",
"application/json",
"text/json",
"application/*+json"
],
```

The api works as expected with application/json as contenttype.

**Comment by RSuter** [comment] 2019-02-28 10:27
So is this what you expect? Or do you want a different outcome?

**Comment by LockTar** [comment] 2019-02-28 10:37
I was only expecting "application/json" because that is in the Consumes attribute.

**Comment by RSuter** [comment] 2019-02-28 17:09
I think the other types are registered globally in asp.net core startup or introduced by the used api convention

**Comment by LockTar** [comment] 2019-03-01 09:23
I think "application/json-patch+json" and "application/*+json" are part of the default then. I can't find anything in the [documentation](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/formatting?view=aspnetcore-2.2) about this.

**Comment by TheSilvermind** [comment] 2019-03-01 12:26
It doesn't matter if they are globally added, because the way asp core works is that if you have a `Consumes` attribute, it will only accept that type. So it makes sense to support this.

**Comment by LockTar** [comment] 2019-03-01 13:54
> It doesn't matter if they are automatically added globally, because the way asp core works is that if you have a Consumes attribute, it will only accept that type. So it makes sense to support this feature. This is easily tested btw.

@TheSilvermind  So… You would expect as well that if you have a Consume attribute `[Consumes("application/json")]` that you would only see the following?
```json
"consumes": [
"application/json"
]
```

**Comment by TheSilvermind** [comment] 2019-03-01 14:08
Yes, because if I apply the attribute and choose another mime type in the swagger 'try it out' functionallity, an exception is thrown that the provided mime type is not supported.

**Comment by RSuter** [comment] 2019-03-01 14:27
These mime types are reported by ASP.NET Core - so I think they are part of the default API Convention or automatically added...

**Comment by TheSilvermind** [comment] 2019-03-01 15:16
@RSuter @LockTar Sorry, you're right. I wasn't paying proper attention. It seems it was the text mime-type that caused problems, but that one seems no longer generated as previously reported.

**Closed** 2019-03-18 21:21 UTC
Labels: project: NSwag.SwaggerGeneration.WebApi, type: enhancement

**Comment by cdutcher** [comment] 2019-06-11 04:29
I'm not seeing [Consumes("text/plain")] respected.  Using NSwag.AspNetCore 12.3.

![image](https://user-images.githubusercontent.com/1753796/59243840-fec80500-8bdf-11e9-8649-a09fee606eff.png)
`        [Consumes("text/plain")]
        public async Task<IActionResult> Cypher([FromBody] string query)`

**Comment by kbsanders** [comment] 2020-02-23 18:16
It appears that for OpenAPI spec generation, the MIME type for content is hardcoded to `application/json` (or `application/octet-stream` for binary files).

https://github.com/RicoSuter/NSwag/blob/4e94b9d2bd558eb7bc2fa5f944b6a3ff08d62c68/src/NSwag.Core/OpenApiResponse.cs#L73-L86

My API will produce JSON:API formatted documents so I need to be able to set the content type to `application/vnd.api+json`.

Currently, the only way I have found to achieve this is via a PostProcess action where I traverse down through the Operations and Responses of the generated spec and remove/replace `application/json` keyed Content items with `application/vnd.api+json`.

```csharp
services.AddOpenApiDocument(config =>
{
    config.PostProcess = document =>
    {
        const string fromKey = "application/json";
        const string toKey = "application/vnd.api+json";

        foreach (var o in document.Operations)
        {
            foreach (var r in o.Operation.Responses)
            {
                if (r.Value.Content.TryGetValue(fromKey, out var value))
                {
                    r.Value.Content.Remove(fromKey);
                    r.Value.Content.Add(toKey, value);
                }
            }
        }
    }
});
```

**Comment by silvairsoares** [comment] 2020-03-11 18:04
I have the same problem ([Consumes ("text / plain")] ignored). I even opened [this question](https://stackoverflow.com/questions/60637029/how-to-enable-the-text-plain-content-type-in-the-documentation-generated-by-ns?noredirect=1#comment107281919_60637029) on the stackoverflow in an attempt to get some help.

**Comment by mhx8** [comment] 2024-11-11 14:28
@silvairsoares try to remove `[FromBody]` Attribute as mentioned here: [AspNetCoreOpenApiDocumentGenerator](https://github.com/RicoSuter/NSwag/wiki/AspNetCoreOpenApiDocumentGenerator)

then use `OpenApiBodyParameterAttribute` instead of `ConsumeAttribuite`. Then everything should work as expected 😊
