### ISSUE TITLE
(TypeScriptGenerator) Change Http to HttpClient

### ISSUE THREAD

**Issue by zuckerthoben** [RSuter/NSwag#958] opened 2017-09-21 11:55 UTC
[Enhancement]

In a project that uses NSwag we are using JWT based authorization between an Angular SPA and an ASP.Net Core Web Api. The best practice to set the default request header is to use HTTP interceptors and add the header there. See: https://offering.solutions/blog/articles/2017/07/19/angular-2-new-http-interface-with-interceptors/ 

Currently the injected http client is Http, which doesnt offer the needed features that HttpClient offers. The generated TypeScript client would strongly benefit from the newer HttpClient.

**Comment by RSuter** [comment] 2017-09-21 12:04
Duplicate of https://github.com/RSuter/NSwag/issues/872

**Comment by RSuter** [comment] 2017-09-21 12:04
This is planned and will (hopefully) come soon

**Closed** 2017-10-10 18:43 UTC
Labels: duplicate

**Comment by RSuter** [comment] 2017-10-10 18:45
The docs have been updated: https://github.com/RSuter/NSwag/wiki/SwaggerToTypeScriptClientGenerator#angular

Test with CI builds: https://ci.appveyor.com/project/rsuter/nswag-25x6o

Please report any problems, suggestions, etc. thank you.

**Comment by RSuter** [comment] 2017-10-11 11:04
![image](https://user-images.githubusercontent.com/2603405/31437171-b0773a68-ae84-11e7-965f-51648d04fe7f.png)

**Comment by zuckerthoben** [comment] 2017-10-11 11:29
I just installed the CI NSwagStudio build and tried the new settings. Looks great. Thank you a lot.
