### ISSUE TITLE
NSwagStudio generating wrong method signature

### ISSUE THREAD

**Issue by andrecarlucci** [RSuter/NSwag#842] opened 2017-07-12 17:57 UTC
Hi guys,

I have these routes in my asp.net core:

```cs
/api/{subscriptionId}/sites 
public IActionResult List(string searchString);  
```

```cs
/api/sites 
public IActionResult ListAll(string subscriptionIdFilter = null, string searchString = null);
```

NSwagStudio is generates the first method just fine, but it is adding a phantom parameter called subscriptionId to the second one:

```cs
public async Task<ListViewModelOfSiteItem> ListAllAsync(string subscriptionId, string subscriptionIdFilter = null, string searchString = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
```

This method is calling the first's method endpoint, nswagstudio is somehow mixing them two. Or maybe I'm doing something wrong...?

Any thoughts?

**Comment by RSuter** [comment] 2017-07-12 18:09
Theres an option to ignore unused path parameters...

**Comment by andrecarlucci** [comment] 2017-07-12 18:13
Hi @RSuter,

But I don't want to ignore anything, I need both methods and their optional parameters.
What do you mean exactly?
Tks!

**Comment by RSuter** [comment] 2017-07-12 18:19
The problem is that you have this signature

    /api/{subscriptionId}/sites 
    public IActionResult List(string searchString);  

ie there is a `subscriptionId` path parameter which is not available as parameter in the method. By default NSwag generates and adds this parameter even if it is not a method parameter. You can disable this behavior with by setting `AddMissingPathParameters` to false

**Comment by andrecarlucci** [comment] 2017-07-12 18:26
This parameter is set on the controller via an action filter.
NSawg adds it to very call as you said, which is perfectly fine and useful for me: the caller has to inform the subscription.
So far so good.

My problem is in the second method, not in the first one. There is no `subscriptionId` in the route and NSwag adds it anyway :(

**Comment by RSuter** [comment] 2017-07-12 18:28
Ah ok, this is strange. Can you provide a sample controller class where i can reproduce this?

**Comment by andrecarlucci** [comment] 2017-07-12 21:01
The code on #843 also generates the parameter problem. 

I guess that as the URL is appended, the "{subscriptionId}" appears there and then the required parameter is generated.

**Comment by RSuter** [comment] 2017-07-12 21:03
Yes this is the problem... For now remove the route on the controller and specify all routes manually on the action - or dont use absolute routes on the actions when a ctrl route is set

**Comment by RSuter** [comment] 2017-07-12 21:13
Can we close this and fix the other one?

**Comment by andrecarlucci** [comment] 2017-07-12 21:19
Yeap, sounds good.

**Closed** 2017-07-12 21:24 UTC
