### ISSUE TITLE
HTTP 202 C# generated client throws exception

### ISSUE THREAD

**Issue by aaronhudon** [RSuter/NSwag#1303] opened 2018-04-25 17:42 UTC
Using NSwag.MSBuild 11.17.0

Code generation command:
`<Exec Command="$(NSwagExe) swagger2csclient /input:$(ProjectDir)\XXX.swagger.json /output:$(ProjectDir)\XXX.generated.cs /Namespace:XXX /ClientBaseClass:XXX /UseHttpRequestMessageCreationMethod:true /ConfigurationClass:XXX /UseHttpClientCreationMethod:true /GenerateOptionalParameters:true /ClassStyle:Poco" />`

The C# generated code for a 202 response always throws an exception.  Is this by design?  2xx codes are supposed to be non error.

Generated code looks like:

```
if (status_ == "202") 
{
	var responseData_ = await response_.Content.ReadAsStringAsync().ConfigureAwait(false); 
	var result_ = default(xxx); 
	try
	{
		result_ = Newtonsoft.Json.JsonConvert.DeserializeObject<xxx>(responseData_, _settings.Value);
	} 
	catch (System.Exception exception_) 
	{
		throw new SwaggerException("Could not deserialize the response body.", (int)response_.StatusCode, responseData_, headers_, exception_);
	}
	throw new SwaggerException<xxx>("A server side error occurred.", (int)response_.StatusCode, responseData_, headers_, result_, null);  // <-- ALWAYS THROWING EXCEPTION
}
```

**Comment by jeremyVignelles** [comment] 2018-04-26 13:01
Hello,
I think this is a duplicate of #1259 : NSwag needs to understand that 202, 204... are success as well.

**Closed** 2018-04-26 13:59 UTC
