### ISSUE TITLE
Process is terminated due to StackOverflowException

### ISSUE THREAD

**Issue by Flo5k5** [RSuter/NSwag#968] opened 2017-09-28 15:45 UTC
Hi, 

I was previously using NSwag 11.7.2 but i'm having an issue since i updated to NSwag 11.8.2. 
I got this error even when using a basic HelloWorld Controller. 
![2017-09-28_17h38_23](https://user-images.githubusercontent.com/3023852/30975991-e247921a-a473-11e7-81ef-a332e19b88fb.png)

In visual studio, i am using "NSwag.MSBuild" and i get "Process is terminated due to StackOverflowException".

Do you have any idea about what's happening?

**Comment by RSuter** [comment] 2017-09-28 15:51
I suspect this is a recursion in the AssemblyLoader class, can you provide this sample project?

**Comment by RSuter** [comment] 2017-09-28 16:03
Try with the binaries (NSwag.zip) from this CI build (as soon as it's built): 

https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/2701/artifacts

Btw: Is "Bos.Api.dll" in the output directory (does this file exist)?

**Comment by RSuter** [comment] 2017-09-28 16:05
And I think this StackOverflow error and the error in your screenshot are not the same. The error in the screenshot is probably because a DLL is missing... The StackOverflow may come from the bug which is fixed in the linked commit.

**Comment by Flo5k5** [comment] 2017-09-28 16:16
Here is the requested sample: 
[Sample.zip](https://github.com/RSuter/NSwag/files/1341581/Sample.zip)

I will try with the provided CI build. 
Yes, the dll exist in the folder. 

Thanks for your help.

**Comment by RSuter** [comment] 2017-09-28 16:18
With this latest fix it works for me: 

![image](https://user-images.githubusercontent.com/2603405/30977979-71a6e456-a479-11e7-87b2-ad844daa7963.png)

**Comment by RSuter** [comment] 2017-09-28 16:19
Its important to "dotnet publish" instead of only "dotnet build"

**Comment by RSuter** [comment] 2017-09-28 16:22
With the current release (v11.8.2) it also works for me... I think it was the "/" in your path which must be omitted. 

However I think your sample project does not reproduce the StackOverflow problem...

**Comment by RSuter** [comment] 2017-09-28 16:26
I will release v11.8.3 now, so you can check if this fix solved your problem with your NSwag.MSBuild integration...

**Comment by Flo5k5** [comment] 2017-09-29 08:49
It's working with the new version 11.8.3!
Many thanks for your help. 

Best regards

**Closed** 2017-09-29 08:49 UTC
Labels: await-repro, bug

**Comment by RSuter** [comment] 2017-09-29 08:53
Ok nice, thanks for testing...
