### ISSUE TITLE
Multiple issues with generated C# code

### ISSUE THREAD

**Issue by wvdvegt** [RSuter/NSwag#1101] opened 2017-12-13 12:18 UTC
Hi

Swagger definition used https://esi.tech.ccp.is/latest/swagger.json (this is a nice & complex one).

It seems to generate 'close' to working code only with SingleClientFroIOperationId as operation mode. 

But still some major issues left (for the rest great work that saves a lotta work).

1. Some of the enums (Color/LabelColor) use names during serialization like #0000fe which are illegal in C#. So better replace these illegal chars by an _.

2. Quite some enums value (like Language in this example) differ in name from the EnumMember value. When passed into a method they are added to the url/body as text using an ToString() like:

`if (language != null) urlBuilder_.Append("language=").Append(Uri.EscapeDataString(System.Convert.ToString(**language**, CultureInfo.InvariantCulture))).Append("&");`

This results in for example "EnUs" being appended instead of the EnumMember value of the language "en-us".

Instead of the enum value, reflection should be used to retrieve the correct value to be appended.

3. It would be nice (for larger definitions like this one) if there was an option to split the current partial client class on the first level of path (so get_alliances/put_alliances etc methods would go into a separate file)

4. The trailing / of paths is lost in the url's used in code. See for example the path 
`"/characters/{character_id}/assets/names/" `
which should results in 
`"/characters/{character_id}/assets/names/?" `
inside 
`Post_characters_character_id_assets_namesAsync() `
but is emitted as 
`"/characters/{character_id}/assets/names?" `
which fails when calling the webservice.

**Comment by wvdvegt** [comment] 2017-12-13 12:43
Possible solution for issue 2

Using the extension methods

```
namespace EveEsi
{
    using System;
    using System.Globalization;
    using System.Reflection;
    using System.Runtime.Serialization;

    /// <summary>
    /// A convert extension.
    /// </summary>
    public static class ConvertExtension
    {
        /// <summary>
        /// An Object extension method that gets a description.
        /// </summary>
        ///
        /// <param name="value"> The value to act on. </param>
        ///
        /// <returns>
        /// The description.
        /// </returns>
        public static string GetDescription(this Object value)
        {
            return value.GetDescription(CultureInfo.InvariantCulture);
        }

        /// <summary>
        /// An Object extension method that gets a description.
        /// </summary>
        ///
        /// <param name="value"> The value to act on. </param>
        /// <param name="ci">    The ci. </param>
        ///
        /// <returns>
        /// The description.
        /// </returns>
        public static string GetDescription(this Object value, CultureInfo ci)
        {
            if (value is Enum)
            {
                string name = Enum.GetName(value.GetType(), value);
                if (name != null)
                {
                    FieldInfo field = value.GetType().GetField(name);
                    if (field != null)
                    {
                        EnumMemberAttribute attr = Attribute.GetCustomAttribute(field, typeof(EnumMemberAttribute)) as EnumMemberAttribute;
                        if (attr != null)
                        {
                            return attr.Value;
                        }
                    }
                }
            }

            return System.Convert.ToString(value, ci);
        }
    }
}

```

It's possible to rewrite generated code like:
System.Convert.ToString(language, CultureInfo.InvariantCulture)
into 
`datasource.GetDescription(CultureInfo.InvariantCulture)`
which retrieves the EnumMember Attribute's value (of if missing or another type then an enum is passed, defaults to 
`System,Convert.ToString()`

Tested on the code that was generated it now creates a correct webservice call url.

**Comment by RSuter** [comment] 2017-12-13 14:48
Enum problem: https://github.com/RSuter/NSwag/issues/1052

**Comment by RSuter** [comment] 2017-12-13 14:50
1. must be fixed in https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema.CodeGeneration/DefaultEnumNameGenerator.cs

**Comment by RSuter** [comment] 2017-12-13 14:52
1. must be fixed in https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema.CodeGeneration/DefaultEnumNameGenerator.cs
2. Duplicate of: https://github.com/RSuter/NSwag/issues/1052
3. Similar to https://github.com/RSuter/NJsonSchema/issues/514 (not yet completed in NSwag)
4. Why is your API not accepting `/characters/{character_id}/assets/names?`? If this is a problem for some APIs we should not trim /

**Comment by wvdvegt** [comment] 2017-12-13 14:59
1) Minus signs are removed for example, so better use the attribute value (it contains the correct value).
   Changing the template used for generating code and use code like i suggested might work better.
2) Issue is broader then just case issues (so not a dupe of #1052). 
4) It just doesn't and API/Definition is not mine.

**Comment by RSuter** [comment] 2017-12-13 15:15
What if we generate the following method in each client class: 

    private string ConvertToString(object value, System.Globalization.CultureInfo cultureInfo)
    {
        if (value is System.Enum)
        {
            string name = System.Enum.GetName(value.GetType(), value);
            if (name != null)
            {
                var field = System.Reflection.IntrospectionExtensions.GetTypeInfo(value.GetType()).GetDeclaredField(name);
                if (field != null)
                {
                    var attribute = System.Reflection.CustomAttributeExtensions.GetCustomAttribute(field, typeof(System.Runtime.Serialization.EnumMemberAttribute)) 
                        as System.Runtime.Serialization.EnumMemberAttribute;
                    if (attribute != null)
                    {
                        return attribute.Value;
                    }
                }
            }
        }

        return System.Convert.ToString(value, cultureInfo);
    }

and use this instead of System.Convert.ToString

**Comment by wvdvegt** [comment] 2017-12-13 15:17
Override the enum's ToString() is probably a better spot for the code.

**Comment by RSuter** [comment] 2017-12-13 15:17
How can you override ToString() of an enum?

**Comment by wvdvegt** [comment] 2017-12-13 15:51
Hi

You're right about ToString(), but the ToString(CultureInfo ci) you can catch with an extension methods.

Your solution also seems pretty ok to me.

Btw nice work NSwagStudio.

You only have to change the 
`System.Convert.ToString(datasource, CultureInfo.InvariantCulture)`
to
`datasource.ToString(CultureInfo.InvariantCulture)`

```
namespace EveEsi
{
    using System;
    using System.Globalization;
    using System.Reflection;
    using System.Runtime.Serialization;

    /// <summary>
    /// A convert extension.
    /// </summary>
    public static class ConvertExtension
    {
        /// <summary>
        /// An Object extension method that gets a description.
        /// </summary>
        ///
        /// <param name="value"> The value to act on. </param>
        /// <param name="ci">    The ci. </param>
        ///
        /// <returns>
        /// The description.
        /// </returns>
        public static string ToString(this Enum value, CultureInfo ci)
        {
            if (value is Enum)
            {
                string name = Enum.GetName(value.GetType(), value);
                if (name != null)
                {
                    FieldInfo field = value.GetType().GetField(name);
                    if (field != null)
                    {
                        EnumMemberAttribute attr = Attribute.GetCustomAttribute(field, typeof(EnumMemberAttribute)) as EnumMemberAttribute;
                        if (attr != null)
                        {
                            return attr.Value;
                        }
                    }
                }
            }

            return System.Convert.ToString(value, ci);
        }
    }
}
```

Using generics also works if you define the method like:

```
       public static string ToString<T>(this T value, CultureInfo ci) where T : struct
        {
        if (typeof(T).IsENum()) {
                        //
                }
        }
```

**Comment by jlewis-rhimat** [comment] 2017-12-19 14:24
Just come across this enum value translation issue on a different swagger definition. 
Using the ConvertToString method in the client instead of System.Convert.ToString resolved the issue.

**Comment by RSuter** [comment] 2017-12-19 16:19
Please retest with latest CI build, and open new separate issues if needed..

**Closed by RSuter** 2017-12-19 16:19 UTC
