### ISSUE TITLE
Authorize attribute - NSwag.MSBuild.CodeGeneration code generation

### ISSUE THREAD

**Issue by grahamehorner** [RSuter/NSwag#1895] opened 2019-01-17 21:30 UTC
The generated code fails to consider the Authorize attribute on a API controller/method,
please consider adding credentials to the client methods/controllers that have a Authorise attribute/requirement.

**Comment by RSuter** [comment] 2019-01-18 10:02
Duplicate of: https://github.com/RSuter/NSwag/issues/1312

Because authentication is handled differently everywhere it is not automatically generated ATM... but there are lot's of possible ways to add this, e.g. 

![image](https://user-images.githubusercontent.com/2603405/51379730-5fab4f80-1b10-11e9-903c-3f89b290f9bc.png)

![image](https://user-images.githubusercontent.com/2603405/51379759-75b91000-1b10-11e9-86da-afa20b0e3a12.png)

then you can add the Authorization header in the CreateHttpRequestMessageAsync in the base class...

**Closed by RSuter** 2019-01-18 10:02 UTC
